LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := loger
LOCAL_SRC_FILES := loger.cpp

LOCAL_C_INCLUDES := $(LOCAL_PATH)	   
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_C_INCLUDES)

include $(BUILD_STATIC_LIBRARY)