LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := device
LOCAL_SRC_FILES := device.c
LOCAL_INC_FILES := device.h
LOCAL_STATIC_LIBRARIES := logger

LOCAL_C_INCLUDES := $(LOCAL_PATH)	   
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_C_INCLUDES)

include $(BUILD_STATIC_LIBRARY)